version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  productpage:
      image: docker/productpage
      expose:
        - "80"
  review:
      image: docker/review
      expose: 
        - "80"
  nginx:
      image: gateway
      ports:
        - "80:80"
